# Generated by Django 3.1.4 on 2020-12-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='category_id',
        ),
    ]
